
version: '3.9'
services:
  db:
    image: postgres:15
    container_name: fintuser_db
    environment:
      - POSTGRES_USER=fintuser
      - POSTGRES_PASSWORD=fintuser
      - POSTGRES_DB=fintuser
    ports:
      - 5430:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

